# Session 1 Home Work

# Q.1 Read version of numpy


In [12]:
import numpy as np
np.__version__

'1.16.2'

# ADD COOMENT Q.2 Read version of pandas

In [13]:

import pandas as pd
pd.__version__

'0.24.2'

In [22]:
# read csv files and convert them to a data frame using pandas

data = pd.read_csv(r'C:\Users\kaur\Desktop\CarData.csv')
cardf = pd.DataFrame(data)

# visualise few rows of dataset
cardf.head()

#let's change the column names to lower case for ease

cardf.columns = cardf.columns.str.lower().str.replace(' ', '_')
cardf

make       model  year                engine_fuel_type  engine_hp  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
5          BMW    1 Series  2012     premium unleaded (required)      230.0   
6          BMW    1 Series  2012     premium unleaded (required)      300.0   
7          BMW    1 Series  2012     premium unleaded (required)      300.0   
8          BMW    1 Series  2012     premium unleaded (required)      230.0   
9          BMW    1 Series  2013     premium unleaded (required)      230.0   
10         BMW    1 Series  2013     premium unleaded (required)      300.0   
11         BMW    1 Series  2013     premium unleaded (required)      230.0   
12         BMW    1 Series  2013     premium unleaded (required)      300.0   
13         BMW    1 Series  2013     premium unleaded (required)      230.0   
14         BMW    1 Series  2013     premium unleaded (required)      230.0   
15         BMW    1 Series  2013     premium unleaded (required)      320.0   
16         BMW    1 Series  2013     premium unleaded (required)      320.0   
17        Audi         100  1992                regular unleaded      172.0   
18        Audi         100  1992                regular unleaded      172.0   
19        Audi         100  1992                regular unleaded      172.0   
20        Audi         100  1992                regular unleaded      172.0   
21        Audi         100  1992                regular unleaded      172.0   
22        Audi         100  1993                regular unleaded      172.0   
23        Audi         100  1993                regular unleaded      172.0   
24        Audi         100  1993                regular unleaded      172.0   
25        Audi         100  1993                regular unleaded      172.0   
26        Audi         100  1993                regular unleaded      172.0   
27        Audi         100  1994                regular unleaded      172.0   
28        Audi         100  1994                regular unleaded      172.0   
29        Audi         100  1994                regular unleaded      172.0   
...        ...         ...   ...                             ...        ...   
11884      BMW          Z3  2001     premium unleaded (required)      225.0   
11885      BMW          Z3  2001     premium unleaded (required)      184.0   
11886      BMW          Z3  2001     premium unleaded (required)      225.0   
11887      BMW          Z3  2002     premium unleaded (required)      225.0   
11888      BMW          Z3  2002     premium unleaded (required)      184.0   
11889      BMW          Z3  2002     premium unleaded (required)      225.0   
11890      BMW        Z4 M  2007     premium unleaded (required)      330.0   
11891      BMW        Z4 M  2007     premium unleaded (required)      330.0   
11892      BMW        Z4 M  2008     premium unleaded (required)      330.0   
11893      BMW        Z4 M  2008     premium unleaded (required)      330.0   
11894      BMW          Z4  2014     premium unleaded (required)      240.0   
11895      BMW          Z4  2014     premium unleaded (required)      300.0   
11896      BMW          Z4  2014     premium unleaded (required)      335.0   
11897      BMW          Z4  2015     premium unleaded (required)      240.0   
11898      BMW          Z4  2015     premium unleaded (required)      300.0   
11899      BMW          Z4  2015     premium unleaded (required)      335.0   
11900      BMW          Z4  2016     premium unleaded (required)      300.0   
11901      BMW          Z4  2016     premium unleaded (required)      240.0   
11902      BMW          Z4  2016     premium unleaded (requi

# Q.3 get the average price of BMW cars in the dataset

In [23]:

# filter the BMW care price

BMWPrice = cardf[cardf['make']== 'BMW']
BMWPrice

# now calculate the avrage price of this car
BMWPrice.msrp.mean()

61546.76347305389

# Q.4 Calculate the number of missing values in "EngineHP" after 2015 (including 2015)

In [30]:
# filter the data to take out Engine HP and from year 2015 on

HP2015on = cardf[(cardf['year'] >= 2015)]
HP2015on

# take out the Engine HP column
HP = HP2015on['engine_hp']

# calculate the total null values
HP.isnull().sum()


51

# Q.5 Does the mean price change after filling missing values? 

In [41]:
# Calculate the average "Engine HP" in the dataset
mean_hp_before = cardf.engine_hp.mean()
mean_hp_before

249.38607007176023

In [39]:
# Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
cardf.engine_hp.fillna(249.38)

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
5        230.0
6        300.0
7        300.0
8        230.0
9        230.0
10       300.0
11       230.0
12       300.0
13       230.0
14       230.0
15       320.0
16       320.0
17       172.0
18       172.0
19       172.0
20       172.0
21       172.0
22       172.0
23       172.0
24       172.0
25       172.0
26       172.0
27       172.0
28       172.0
29       172.0
         ...  
11884    225.0
11885    184.0
11886    225.0
11887    225.0
11888    184.0
11889    225.0
11890    330.0
11891    330.0
11892    330.0
11893    330.0
11894    240.0
11895    300.0
11896    335.0
11897    240.0
11898    300.0
11899    335.0
11900    300.0
11901    240.0
11902    335.0
11903    394.0
11904    394.0
11905    394.0
11906    300.0
11907    300.0
11908    300.0
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: engine_hp, Length: 11914, dtype: float64

In [43]:
# Now, calcualte the average of "Engine HP" again.
mean_hp_after = cardf.engine_hp.mean()
mean_hp_after

249.38607007176023

In [45]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


# Q.6 Sum of elements of the inverse matrix

In [53]:
#Select all the "Rolls-Royce" cars from the dataset

RR = cardf[cardf['make']== 'Rolls-Royce']
RR


make                   model  year             engine_fuel_type  \
2921   Rolls-Royce                Corniche  2001  premium unleaded (required)   
3505   Rolls-Royce                    Dawn  2016  premium unleaded (required)   
5275   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5276   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5277   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5278   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5279   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5280   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5281   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5282   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5283   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
5284   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
7443   Rolls-Royce               Park Ward  2001  premium unleaded (required)   
7444   Rolls-Royce               Park Ward  2002  premium unleaded (required)   
7553   Rolls-Royce           Phantom Coupe  2014  premium unleaded (required)   
7554   Rolls-Royce           Phantom Coupe  2015  premium unleaded (required)   
7555   Rolls-Royce           Phantom Coupe  2016  premium unleaded (required)   
7556   Rolls-Royce  Phantom Drophead Coupe  2014  premium unleaded (required)   
7557   Rolls-Royce  Phantom Drophead Coupe  2015  premium unleaded (required)   
7558   Rolls-Royce  Phantom Drophead Coupe  2016  premium unleaded (required)   
7559   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7560   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7561   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7562   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7563   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
7564   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
9431   Rolls-Royce           Silver Seraph  2001  premium unleaded (required)   
9432   Rolls-Royce           Silver Seraph  2002  premium unleaded (required)   
11448  Rolls-Royce                  Wraith  2014  premium unleaded (required)   
11449  Rolls-Royce                  Wraith  2015  premium unleaded (required)   
11450  Rolls-Royce                  Wraith  2016  premium unleaded (required)   

       engine_hp  engine_cylinders transmission_type     driven_wheels  \
2921       325.0               8.0         AUTOMATIC  rear wheel drive   
3505       563.0              12.0         AUTOMATIC  rear wheel drive   
5275       563.0              12.0         AUTOMATIC  rear wheel drive   
5276       563.0              12.0         AUTOMATIC  rear wheel drive   
5277       563.0              12.0         AUTOMATIC  rear wheel drive   
5278       563.0              12.0         AUTOMATIC  rear wheel drive   
5279       563.0              12.0         AUTOMATIC  rear wheel drive   
5280       563.0              12.0         AUTOMATIC  rear wheel drive   
5281       563.0              12.0         AUTOMATIC  rear wheel drive   
5282       563.0              12.0         AUTOMATIC  rear wheel drive   
5283       563.0              12.0         AUTOMATIC  rear wheel drive   
5284       563.0              12.0         AUTOMATIC  rear wheel drive   
7443       322.0              12.0         AUTOMATIC  rear wheel drive   
7444       322.0              12.0         AUTOMATIC  rear wheel drive   
7553       453.0              12.0         AUTOMATIC  rear wheel drive   
7554       453.0              12.0         AUTOMATIC  rear wheel drive   
7555       453.0              12.0         AUTOMATIC  rear wheel drive   
7556       453.0              12.0         AUTOMATIC  rear wheel drive   
7557       453.

In [55]:
# Select only columns "Engine HP", "Engine Cylinders", "highway MPG".

RR = RR[['engine_hp','engine_cylinders','highway_mpg']]
RR

engine_hp  engine_cylinders  highway_mpg
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [111]:
# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
NewRR = RR.drop_duplicates()
NewRR

engine_hp  engine_cylinders  highway_mpg
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [113]:
# Get the underlying NumPy array. Let's call it X.
X = np.log1p(NewRR)
X

X = X.values
X


array([[5.78689738, 2.19722458, 2.77258872],
       [6.33505425, 2.56494936, 2.99573227],
       [6.33505425, 2.56494936, 3.09104245],
       [6.33505425, 2.56494936, 3.04452244],
       [5.77765232, 2.56494936, 2.77258872],
       [6.1180972 , 2.56494936, 2.99573227],
       [6.43775165, 2.56494936, 3.09104245]])

In [115]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
tr = X.T
tr

array([[5.78689738, 6.33505425, 6.33505425, 6.33505425, 5.77765232,
        6.1180972 , 6.43775165],
       [2.19722458, 2.56494936, 2.56494936, 2.56494936, 2.56494936,
        2.56494936, 2.56494936],
       [2.77258872, 2.99573227, 3.09104245, 3.04452244, 2.77258872,
        2.99573227, 3.09104245]])

In [116]:
# now matrix-matrix multiplication
XTX = tr.dot(X)
XTX

array([[266.14394441, 108.4868952 , 128.1385479 ],
       [108.4868952 ,  44.30158708,  52.23713346],
       [128.1385479 ,  52.23713346,  61.70152393]])

In [117]:
# invert XTX
res = XTX.T
res

#reversed_arr = XTX[::-1]
#reversed_arr

array([[266.14394441, 108.4868952 , 128.1385479 ],
       [108.4868952 ,  44.30158708,  52.23713346],
       [128.1385479 ,  52.23713346,  61.70152393]])

In [118]:
# What's the sum of all the elements of the result?
res.sum()

949.8722085295748

# Q.7 Normal equation


In [94]:
#Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].

y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [119]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w=res*tr*y
w


ValueError: operands could not be broadcast together with shapes (3,3) (3,7) 